carrerProgress/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from rest_framework.authtoken import views as authv

app_name = 'carrerProgress'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='carrerProgress/login.html')),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^enroll/(?P<pk>[0-9]+)/$', views.DetailEnrolled.as_view(), name='enroll'),
    url(r'^listSubjects/$', views.ListSubjects.as_view()),
    url(r'(?P<pk>[0-9]+)/$', views.DetailsView.as_view() ,name='detail'),
    url(r'^api-token-auth/$', authv.obtain_auth_token)
]

isiProgress/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('carrer/', include('carrerProgress.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

carrerProgress/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.contrib.auth.models import User


class professor (models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__ (self):
        return self.name + ' ' + self.last_name

class subjects (models.Model):
    name =models.CharField(max_length=200)
    year = models.IntegerField(default=1)
    subject_professor = models.ForeignKey(professor, on_delete=models.CASCADE)
    requirements = JSONField(null=True)

    def __str__ (self):
        return self.name

class enrolled (models.Model):
    state = models.CharField(max_length=200, default="Sin Cursar")
    calification = models.IntegerField(default=0)
    year = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.ForeignKey(subjects, on_delete=models.CASCADE)

    def __str__ (self):
        return self.subject.name + ' ' + self.user.username

class parcial (models.Model):
    calification = models.IntegerField(default=0)
    date = models.DateTimeField('Parcial date')
    parcial_subject = models.ForeignKey(subjects, on_delete=models.CASCADE)

    def __str__ (self):
        return self.date

carrerProgress/views.py
from django.shortcuts import(
    render,
    get_object_or_404
)

from django.http import HttpResponseRedirect
from django.http import Http404
from django.template import loader
from django.views import View
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

# API
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from .serializers import EnrolledSerializer, SubjectSerializer

# Import current User
from django.contrib.auth.models import User

# Models Import
from .models import(
    subjects,
    enrolled
)

class ListEnrolled(APIView):

    def get_objects(self, user):
        try:
            return enrolled.objects.filter(user=user)
        except enrolled.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        enroll = self.get_objects(pk)
        serializer = EnrolledSerializer(enroll, many=True)
        return Response(serializer.data)

    # Post necesario para la actualizacion del estado de la materia en curso
    def post(self, request, format=None):
        serializer = EnrolledSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class DetailEnrolled(APIView):

    def get_object(self, pk):
        try:
            return enrolled.objects.get(subject=pk)
        except enrolled.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        enrolled_return = self.get_object(pk)
        serializer = EnrolledSerializer(enrolled_return)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        enrrolled_put = self.get_object(pk)
        serializer = EnrolledSerializer(enrrolled_put, data=request.data)
        if serializer.is_valid():
            serializer.save
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ListSubjects(APIView):

    def get(self, request, format=None):
        subject = subjects.objects.all()
        serializer = SubjectSerializer(subject, many=True)
        return Response(serializer.data)


# Non API Views


class DetailsView(LoginRequiredMixin, View):
    login_url = '/carrer/login'
    redirect_field_name = 'redirect_to'
    template_name = 'carrerProgress/details.html'
    model = subjects
    context = {}

    def set_context(self):
        current_user = self.request.user
        id_ = self.kwargs.get("pk")
        self.context = {
            "subjects": (subjects.objects.filter(id=id_)).first(),
            "enrolled": (enrolled.objects.filter(user=current_user)).filter(subject=id_).first()
        }

    def get(self, request, *args, **kwargs):
        self.set_context()
        print( self.context)
        return render(request, self.template_name, self.context)

class IndexView(LoginRequiredMixin,View):
    login_url = '/carrer/login'
    redirect_field_name = 'redirect_to'
    template_name = 'carrerProgress/index.html'
    context = {}

    def set_context(self):
        self.context = {
            "PrimerAnio": subjects.objects.filter(year=1),
            "SegundoAnio": subjects.objects.filter(year=2),
            "TercerAnio": subjects.objects.filter(year=3),
            "CuartoAnio": subjects.objects.filter(year=4),
            "QuintoAnio": subjects.objects.filter(year=5),
            "PrimerAnioAprobado": self.get_Aprobed(1),
            "SegundoAnioAprobado": self.get_Aprobed(2),
            "TercerAnioAprobado": self.get_Aprobed(3),
            "CuartoAnioAprobado": self.get_Aprobed(4),
            "QuintoAnioAprobado": self.get_Aprobed(5),
        }

    def get_Aprobed(self, year):
        current_user = self.request.user
        filter_aprobed = enrolled.objects.filter(user=current_user)
        if filter_aprobed:
            filter_aprobed = filter_aprobed.filter(subject__year=year)
            total = len(subjects.objects.filter(year=year))
            if total > 0:
                filter_aprobed = filter_aprobed.filter(state="Aprobada")
                return {
                    "total": (len(filter_aprobed)/total)*100,
                    "materias": filter_aprobed
                }
        else: pass

    def get(self, request, *args, **kwargs):
        self.set_context()
        return render(request, self.template_name, self.context)

carrerProgress/templates/base.html
<html>
	<head>
		<!-- Imports -->

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
		<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
		<script src="http://code.jquery.com/jquery.min.js"></script>

		{% block title %}
		<title>IsiProgress</title>
		{% endblock %}

		
		<style>

			#titleISI {
				text-align: center;
			}
			body {
				font-family: "Roboto";
			}
			th {
				text-align: center;
				max-width:200px;
				align-content: center; 
			}
			.listofsubjects {
				-webkit-columns: 200px 3;
				-moz-columns: 200px 3;
				columns: 300px 3;
			}
			a {
					font-size: 14px;
			}
			.progress_bar {
					align-content: center;
					max-width: 300px;
					padding-left: 50px;
			}
			 li{
					list-style-type: none;
			}
		</style>
	{% load static %}
	<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
	<script src="{% static 'functions.js' %}"></script>
	<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
		{% block head %}
		{% endblock %}
	</head>
	<body>

		<div class="jumbotron jumbotron-fluid bg container-fluid"  id="top">
			<div class="container" id="titleISI">
				<a href="{% url 'carrerProgress:index' %}" style="text-decoration:none"><h1 class="display-4 font-weight-bold" style="color:white;font-size:150px;" >ISI-Progress</h1></a>
				{% block subtitle %}
					<h2 style="color:white;font-size:50px;">{{ user.username }}</h2>
				{% endblock %}
				</br>
				{% if user.is_authenticated %}
					<a class="btn btn-outline-light" style="width:152" href="{% url 'carrerProgress:index' %}"><i class="fas fa-home"></i> Home </a>
					<a class="btn btn-outline-info" style="width:152" href="http://sysacadweb.frre.utn.edu.ar/"><i class="fas fa-book"></i> Sysacad</a>
					<a class="btn btn-outline-success" style="width:152" href="http://frre.cvg.utn.edu.ar"><i class="fas fa-book-reader"></i> Campus Virtual</a>
					<a class="btn btn-outline-light" style="width:152" href="http://frre.utn.edu.ar"><i class="fas fa-university"></i> UTN</a>
					<a class="btn btn-outline-danger" style="width:152" href="{% url 'carrerProgress:logout'%}"><i class="fas fa-sign-out-alt"></i> Logout</a>
				{% else %}
					<a class="btn btn-outline-info" style="width:152" href="http://sysacadweb.frre.utn.edu.ar/"><i class="fas fa-book"></i> Sysacad</a>
					<a class="btn btn-outline-success" style="width:152" href="http://frre.cvg.utn.edu.ar"><i class="fas fa-book-reader"></i> Campus Virtual</a>
					<a class="btn btn-outline-light" style="width:152" href="http://frre.utn.edu.ar"><i class="fas fa-university"></i> UTN</a>
				{% endif %}
				</br>
			</div>
		</div>
		{% block body %}

		{% endblock %}

	</body>
</html>

carrerProgress/templates/carrerProgress/details.html
{% extends 'base.html' %}

{% block title %}
	<title>{{ subjects.name }}</title>
{% endblock %}

{% block subtitle %}
	<h2 style="color:white;font-size:50px;">{{ subjects.name }}</h2>
{% endblock %}

{% block body %}
<center>
	<div class=container" style="max-width:1300">
		<div class="table-responsive">
			<table class="table">
					<thead class="thead-dark">
						<tr>
							<th style="text-align:center">
									<h3>Usuario</h3>
							</th>
							<th style="text-align:center">
									<h3>Incripcion</h3>
							</th>
							<th style="text-align:center">
									<h3>Anio</h3>
							</th>
							<th style="text-align:center">
									<h3>Estado</h3>
							</th>
							<th style="text-align:center">
								<h3>Calificacion</h3>
							</th>
							<th style="text-align:center">
								<h3> Jefe de Catedra </h3>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<th>
								<p style="font-size:20">{{ user.get_username }}</p>
							</th>
							<th>
								<p style="font-size:20">{{ enrolled.year }}</p>
							</th>
							<th>
								<p style="font-size:20">{{ enrolled.subject.year }}</p>
							</th>
							<th>
								{% if enrolled.state %}
									<p style="font-size:20">{{ enrolled.state }}</p>
								{% else %}
									<p style="font-size:20">Sin cursar</p>
								{% endif %}
							</th>
							<th>
								<p style="font-size:20">{{ enrolled.calification }}</p>
							</th>
							<th>
								<p style="font-size:20">{{ subjects.subject_professor }}</p>
							</th>
						</tr>
					</tbody>
			</table>
			<div id="vue">
				<div class="container" v-if="seen">
					<div class="table-responsive">
							<table class="table" style="max-width:1300">
								<thead class="thead-dark">
									<tr>
										<h3> Requerimientos</h3>
									</tr>
									<tr>
										<th>
											<h4> Materias Regularizadas: </h4>
										</th>
										<th v-if="materiasA.show">
											<h4> Materias Aprobadas: </h4>
										</th>
									</tr>
								</thead>
								<tbody>
									</tr>
										<th>
											<ul class="list-group">
												<li v-for="materia in materias" class="list-group-item ">
													<h5>${ materia.name }</h5>
												</li>
											</ul>
										</th>
										<th v-if="materiasA.show">
											<ul class="list-group">
												<li v-for="materia in materiasA.elements" class="list-group-item">
													<h5>${ materia.name }</h5>
												</li>
											</ul>
										</th>
									</tr>
								</body>
							</ul>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</center>
<script>

	var sub_req = data_set('{{ subjects.requirements }}'); 

	var app = new Vue({
	el: "#vue",
	delimiters: ["${","}"],
	data: {
		seen: sub_req.show,
		materias: sub_req.requirements.Regularizadas,
		materiasA: {
			elements: sub_req.requirements.Aprobadas,
			show: isEmpty(sub_req.requirements.Aprobadas) 
		}
	}
});

</script>

<style>
	#titleISI {
		text-align: center;
	}
	th {
		text-align: center;
		max-width:200px;
		align-content: center; 
	}
	body {
		font-family: 'Roboto';
		font-size: 22px;
	}
</style>

{% endblock %}

carrerProgress/templates/carrerProgress/index.html
{% extends "base.html" %}

{% block body %}
<body>
	<div class="table-responsive">
		<table class="table">
			<thead class="thead-dark">
				<tr>
					<th scope="col">
							Primer Anio
							<div class="progress ">
									<div class="progress-bar" role="progressbar" style="width: {{ PrimerAnioAprobado.total }}%"  aria-valuemin="0" aria-valuemax="{{ PrimerAnio|length }}"></div>
							</div>
					</th>
					<th scope="col">
							Segundo Anio
							<div class="progress">
									<div class="progress-bar" role="progressbar" style="width: {{ SegundoAnioAprobado.total }}%" aria-valuemin="0" aria-valuemax="{{ SegundoAnio|length }}"></div>
							</div>
					</th>
					<th scope="col">
							Tercer Anio
							<div class="progress">
									<div class="progress-bar" role="progressbar" style="width: {{ TercerAnioAprobado.total }}%"  aria-valuemin="0" aria-valuemax="{{ TercerAnio|length }}"></div>
							</div>
					</th>
					<th scope="col">
							Cuarto Anio
							<div class="progress">
									<div class="progress-bar" role="progressbar" style="width: {{ CuartoAnioAprobado.total }}%"  aria-valuemin="0" aria-valuemax="{{ CuartoAnio|length }}"></div>
							</div>
					</th>
					<th scope="col"> 
							Quinto Anio
							<div class="progress">
									<div class="progress-bar" role="progressbar" style="width: {{ QuintoAnioAprobado.total }}%"  aria-valuemin="0" aria-valuemax="{{ QuintoAnio|length }}"></div>
							</div>
					</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>
					{% for subjects in PrimerAnio %}
						<li>
							<a  class="list-group-item list-group-item-action list-group-item-active"href="{% url 'carrerProgress:detail' subjects.id %}"> {{ subjects.name }}</a>
						</li>
						</br>
					{% endfor %}
					</th>
					<th>
					{% for subjects in SegundoAnio %}
						<li>
							<a  class="list-group-item list-group-item-action" href="{% url 'carrerProgress:detail' subjects.id %}"> {{ subjects.name }}</a>
						</li>
						</br>
					{% endfor %}
					</th>
					<th>
					{% for subjects in TercerAnio %}
						<li>
							<a class="list-group-item list-group-item-action"  href="{% url 'carrerProgress:detail' subjects.id %}"> {{ subjects.name }}</a>
						</li>
						</br>
					{% endfor %}
					</th>
					<th>
					{% for subjects in CuartoAnio %}
						<li>
							<a  class="list-group-item list-group-item-action" href="{% url 'carrerProgress:detail' subjects.id %}"> {{ subjects.name }}</a>
						</li>
						</br>
					{% endfor %}
					</th>
					<th>
					{% for subjects in QuintoAnio %}
						<li>
							<a  class="list-group-item list-group-item-action" href="{% url 'carrerProgress:detail' subjects.id %}"> {{ subjects.name }}</a>
						</li>
						</br>
					{% endfor %}
					</th>
				</tr>
			</tbody>
		</table>
		</div>
	</div>
{% endblock %}

carrerProgress/templates/carrerProgress/login.html
<html>
		{% extends 'base.html' %}
	<head>
			<title>Login</title>
	</head>
	<body>
			{% block body %}
			<center>
				<div class="jumbotron">
				<form method="post">
					{% csrf_token %}
					{{ form.as_p }}
				<button class="btn btn-outline-success" type="submit" value="login">Loggin</button>
				</form>
</div>
			</center>
			{% endblock %}
					
	</body>
	
<style>
</style>
</html>